
taxi_co_homepage:
    path:     /
    defaults: { _controller: TaxiCoBundle:Default:index }

taxi_co_addRec:
    path:     /add
    defaults: { _controller: TaxiCoBundle:Reclamation:ajouterReclamation }

taxi_co_listRec:
    path:     /list
    defaults: { _controller: TaxiCoBundle:Reclamation:afficherReclamation }

taxi_co_deletetRec:
    path:     /delete/{id}
    defaults: { _controller: TaxiCoBundle:Reclamation:supprimerReclamation }

taxi_co_updateRec:
    path:     /update/{id}
    defaults: { _controller: TaxiCoBundle:Reclamation:modifierReclamation }

taxi_co__mailRec:
    path:     /mail
    defaults: { _controller: TaxiCoBundle:Reclamation:mailReclamation }