taxi_co_homepage:
    path:     /
    defaults: { _controller: TaxiCoBundle:Default:index }
vehicule_homepage:
    path:     /
    defaults: { _controller: TaxiCoBundle:Default:index }
vehicule_ajoutvehicule:
    path:     /ajoutvehicule
    defaults: { _controller: TaxiCoBundle:Vehicule:ajoutvehicule }
vehicule_listVehicule:
    path:     /listvehicule
    defaults: { _controller: TaxiCoBundle:Vehicule:listVehicule }
vehicule_taxi:
    path:     /listtaxi
    defaults: { _controller: TaxiCoBu