taxi_co_colis:
    resource: "@TaxiCoBundle/Resources/config/routing/colis.yml"
    prefix:   /colis

taxi_co_homepage:
    path:     /
    defaults: { _controller: TaxiCoBundle:Default:index }

taxi_co_addRec:
    path:     /add
    defaults: { _controller: TaxiCoBundle:Reclamation:ajouterReclamation }

taxi_co_listRec:
    path:     /list
    defaults: { _controller: TaxiCoBundle:Reclamation:afficherReclamation }

taxi_co_deletetRec:
    path:     /delete/{id}
    defaults: { _controller: TaxiCoBundle:Reclamation:supprimerReclamation }

taxi_co_updateRec:
    path:     /update/{id}
    defaults: { _controller: TaxiCoBundle:Reclamation:modifierReclamation }

taxi_co__mailRec:
    path:     /mail
    defaults: { _controller: TaxiCoBundle:Reclamation:mailReclamation }

# For Admin :

taxi_co__backListRec:
    path:     /adminList
    defaults: { _controller: TaxiCoBundle:Reclamation:adminlistRec }

taxi_co__backListCardRec:
    path:     /adminListCard
    defaults: { _controller: TaxiCoBundle:Reclamation:adminlistCardRec }

taxi_co__backDeleteRec:
    path:     /adminDelete/{id}
    defaults: { _controller: TaxiCoBundle:Reclamation:admindeleteRec }

taxi_co__backDeleteCardRec:
    path:     /adminDeleteCard/{id}
    defaults: { _controller: TaxiCoBundle:Reclamation:admindeleteRecCard }

taxi_co__backupdateRec:
    path:     /adminUpdate/{id}
    defaults: { _controller: TaxiCoBundle:Reclamation:adminupdateRec }