category_index:
    path:     /
    defaults: { _controller: "ColisBundle:Category:index" }
    methods:  GET

category_show:
    path:     /{idcatergory}/show
    defaults: { _controller: "ColisBundle:Category:show" }
    methods:  GET

category_new:
    path:     /new
    defaults: { _controller: "ColisBundle:Category:new" }
    methods:  [GET, POST]

category_edit:
    path:     /{idcatergory}/edit
    defaults: { _controller: "ColisBundle:Category:edit" }
    methods:  [GET, POST]

category_delete:
    path:     /{idcatergory}/delete
    defaults: { _controller: "ColisBundle:Category:delete" }
    methods:  DELETE
