evenement_homepage:
    path:     /
    defaults: { _controller: EvenementBundle:Default:index }
Event_Back:
    path:     /showBack
    defaults: { _controller: EvenementBundle:Evenement:showback }
Event_show:
    path:     /show
    defaults: { _controller: EvenementBundle:Evenement:show }
ParticiperEv:
    path:     /ParticiperEv/{idev}
    defaults: { _controller: EvenementBundle:Evenement:ParticiperEv }
QuitterEv:
    path:     /QuitterEv/{idev}
    defaults: { _controller: EvenementBundle:Evenement:QuitterEv }
Event_add:
    path:     /new
    defaults: { _controller: EvenementBundle:Evenement:new }
LoadEvent:
    path:     /load
    defaults: { _controller: EvenementBundle:Evenement:load }
addEvent:
    path:     /add
    defaults: { _controller: EvenementBundle:Evenement:add }
allevent:
    path:     /allevent
    defaults: { _controller: EvenementBundle:EventMobile:allevent }
afficherback:
    path:     /afficherback
    defaults: { _controller: EvenementBundle:Evenement:afficherback }
archiver:
    path:     /archiver/{id}
    defaults: { _controller: EvenementBundle:Evenement:archiver }
desarchiver:
    path:     /desarchiver/{id}
    defaults: { _controller: EvenementBundle:Evenement:desarchiver }
Participer:
    path:     /Participer/{idev}/{iduser}
    defaults: { _controller: EvenementBundle:EventMobile:Participer }
findevent:
    path:     /findevent/{id}
    defaults: { _controller: EvenementBundle:EventMobile:findevent }
listuser:
    path:     /listuser/{iduser}
    defaults: { _controller: EvenementBundle:EventMobile:listuser }
Quitter:
    path:     /Quitter/{idev}/{iduser}
    defaults: { _controller: EvenementBundle:EventMobile:Quitter }
Trier:
    path:     /trier
    defaults: { _controller: EvenementBundle:EventMobile:triEvent }
event_delete:
    path:     /delete
    defaults: { _controller: EvenementBundle:Evenement:delete }
event_modif:
    path:     /modif
    path:     /delete/{id}
    defaults: { _controller: EvenementBundle:Evenement:delete }
event_modif:
    path:     /modif/{id}
    defaults: { _controller: EvenementBundle:Evenement:modif }