Colis:
    type: entity
    table: colis
    indexes:
        ckuser:
            columns:
                - id_expediteur
    id:
        idC:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            column: id_c
            generator:
                strategy: IDENTITY
    fields:
        depart:
            type: string
            nullable: false
            length: 250
            options:
                fixed: false
        destination:
            type: string
            nullable: false
            length: 250
            options:
                fixed: false
        nomExpediteur:
            type: string
            nullable: false
            length: 250
            options:
                fixed: false
            column: nom_expediteur
        nomDestinataire:
            type: string
            nullable: false
            length: 250
            options:
                fixed: false
            column: nom_destinataire
        poids:
            type: float
            nullable: false
            precision: 10
            scale: 0
        etat:
            type: integer
            nullable: false
            options:
                unsigned: false
        idKarhba:
            type: integer
            nullable: false
            options:
                unsigned: false
                default: '0'
            column: id_karhba
        idExpediteur:
            type: integer
            nullable: false
            options:
                unsigned: false
            column: id_expediteur
        telDestinataire:
            type: integer
            nullable: false
            options:
                unsigned: false
            column: tel_destinataire
        mailExpediteur:
            type: string
            nullable: false
            length: 250
            options:
                fixed: false
            column: mail_expediteur
        mailDestinataire:
            type: string
            nullable: true
            length: 250
            options:
                fixed: false
            column: mail_destinataire
    lifecycleCallbacks: {  }
