Commande:
    type: entity
    table: commande
    indexes:
        clientk:
            columns:
                - client
        karhba:
            columns:
                - vehicule
    id:
        idCommande:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            column: id_commande
            generator:
                strategy: IDENTITY
    fields:
        ptDepart:
            type: string
            nullable: false
            length: 250
            options:
                fixed: false
            column: pt_depart
        ptArrivee:
            type: string
            nullable: false
            length: 250
            options:
                fixed: false
            column: pt_arrivee
        prix:
            type: float
            nullable: false
            precision: 10
            scale: 0
        typePaiement:
            type: string
            nullable: false
            length: 250
            options:
                fixed: false
            column: type_paiement
        date:
            type: date
            nullable: false
        time:
            type: time
            nullable: false
    manyToOne:
        client:
            targetEntity: User
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                client:
                    referencedColumnName: id_u
            orphanRemoval: false
        vehicule:
            targetEntity: Vehicule
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                vehicule:
                    referencedColumnName: id_v
            orphanRemoval: false
    lifecycleCallbacks: {  }
