Contrat:
    type: entity
    table: contrat
    indexes:
        chiffour:
            columns:
                - id_chauff
    id:
        idContrat:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            column: id_contrat
            generator:
                strategy: IDENTITY
    fields:
        typeC:
            type: string
            nullable: false
            length: 250
            options:
                fixed: false
            column: type_c
        duree:
            type: integer
            nullable: false
            options:
                unsigned: false
    manyToOne:
        idChauff:
            targetEntity: User
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                id_chauff:
                    referencedColumnName: id_u
            orphanRemoval: false
    lifecycleCallbacks: {  }
