Forum:
    type: entity
    table: forum
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        created:
            type: datetime
            nullable: false
        title:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        content:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        filename:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        filepath:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        modified:
            type: datetime
            nullable: false
        etat:
            type: integer
            nullable: false
            options:
                unsigned: false
        filetype:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
    lifecycleCallbacks: {  }
