Garage:
    type: entity
    table: garage
    indexes:
        id_service_fk:
            columns:
                - id_service
    id:
        idGarage:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            column: id_garage
            generator:
                strategy: IDENTITY
    fields:
        name:
            type: string
            nullable: true
            length: 50
            options:
                fixed: false
        address:
            type: string
            nullable: true
            length: 50
            options:
                fixed: false
        idService:
            type: integer
            nullable: true
            options:
                unsigned: false
            column: id_service
    lifecycleCallbacks: {  }
