Invitation:
    type: entity
    table: invitation
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        emailSender:
            type: string
            nullable: false
            length: 50
            options:
                fixed: false
            column: email_sender
        emailRecipient:
            type: string
            nullable: false
            length: 50
            options:
                fixed: false
            column: email_recipient
    lifecycleCallbacks: {  }
