Rdv:
    type: entity
    table: rdv
    indexes:
        id_chauffeur_fk:
            columns:
                - id_chauffeur
        id_garage_fk:
            columns:
                - id_garage
        id_service_fk:
            columns:
                - id_service
    id:
        idRdv:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            column: id_rdv
            generator:
                strategy: IDENTITY
    fields:
        idChauffeur:
            type: integer
            nullable: true
            options:
                unsigned: false
            column: id_chauffeur
        dateRdv:
            type: date
            nullable: true
            column: date_rdv
        idGarage:
            type: integer
            nullable: true
            options:
                unsigned: false
            column: id_garage
        idService:
            type: integer
            nullable: true
            options:
                unsigned: false
            column: id_service
        status:
            type: string
            nullable: true
            length: 50
            options:
                fixed: false
    lifecycleCallbacks: {  }
