Service:
    type: entity
    table: service
    id:
        idService:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            column: id_service
            generator:
                strategy: IDENTITY
    fields:
        name:
            type: string
            nullable: true
            length: 50
            options:
                fixed: false
    lifecycleCallbacks: {  }
