User:
    type: entity
    table: user
    indexes:
        id_eventfk:
            columns:
                - nom_event
        ptfidid:
            columns:
                - point_fidelite
    uniqueConstraints:
        mail:
            columns:
                - mail
    id:
        idU:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            column: id_u
            generator:
                strategy: IDENTITY
    fields:
        nom:
            type: string
            nullable: true
            length: 250
            options:
                fixed: false
        prenom:
            type: string
            nullable: true
            length: 250
            options:
                fixed: false
        tel:
            type: integer
            nullable: true
            options:
                unsigned: false
        mail:
            type: string
            nullable: false
            length: 250
            options:
                fixed: false
        mdp:
            type: string
            nullable: false
            length: 250
            options:
                fixed: false
        naissance:
            type: string
            nullable: true
            length: 250
            options:
                fixed: false
        creation:
            type: string
            nullable: true
            length: 250
            options:
                fixed: false
        active:
            type: integer
            nullable: true
            options:
                unsigned: false
        image:
            type: string
            nullable: true
            length: 250
            options:
                fixed: false
        type:
            type: string
            nullable: true
            length: 250
            options:
                fixed: false
        cin:
            type: integer
            nullable: true
            options:
                unsigned: false
                default: '0'
        permis:
            type: integer
            nullable: false
            options:
                unsigned: false
                default: '0'
        nomCompte:
            type: string
            nullable: false
            length: 250
            options:
                fixed: false
                default: none
            column: nom_compte
        ribCompte:
            type: integer
            nullable: false
            options:
                unsigned: false
                default: '0'
            column: rib_compte
        experience:
            type: integer
            nullable: false
            options:
                unsigned: false
                default: '0'
        nbrCourse:
            type: integer
            nullable: true
            options:
                unsigned: false
            column: nbr_course
        pointFidelite:
            type: integer
            nullable: false
            options:
                unsigned: false
                default: '0'
            column: point_fidelite
        nomEvent:
            type: string
            nullable: false
            length: 11
            options:
                fixed: false
                default: none
            column: nom_event
    lifecycleCallbacks: {  }
