<?php

namespace ColisBundle\Repository;

/**
 * CategroyColisRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategroyColisRepository extends \Doctrine\ORM\EntityRepository
{
}
