forum_homepage:
    path:     /forum
    defaults: { _controller: ForumBundle:Forum:show }
forum_add:
    path:     /add
    defaults: { _controller: ForumBundle:Forum:addForum }

forum_homepage_back:
    path:     /forumBack
    defaults: { _controller: ForumBundle:Forum:showback }
forum_one:
    path:     /article/{f}
    defaults: { _controller: ForumBundle:Forum:article }
comment:
    path:     /comment/{f}
    defaults: { _controller: ForumBundle:Forum:comment }
archiver:
    path:     /archiver/{id}
    defaults: { _controller: ForumBundle:Forum:archiver }
desarchiver:
    path:     /desarchiver/{id}
    defaults: { _controller: ForumBundle:Forum:desarchiver }
removeSelected:
    path:     /removeSelected/{id}
    defaults: { _controller: ForumBundle:Forum:removeSelected }
edit:
    path:     /edit/{id}
    defaults: { _controller: ForumBundle:Forum:edit }
