<?php

namespace TaxiCoBundle\Repository;

/**
 * RatingReclamationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RatingReclamationRepository extends \Doctrine\ORM\EntityRepository
{
}
