<?php

namespace TaxiCoBundle\Repository;

/**
 * ServiceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ServiceRepository extends \Doctrine\ORM\EntityRepository
{
    public function findDQL()
    {
        $query= $this->getEntityManager()->createQuery
        ("SELECT f FROM EventBundle:Events f where f.nom='mahdi'");
        return $query->getResult();

    }
}