<?php

namespace TaxiCoBundle\Repository;

/**
 * typereclamationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class typereclamationRepository extends \Doctrine\ORM\EntityRepository
{
}
